### ISSUE TITLE
Incomplete results

### ISSUE THREAD

**Issue by ahupp** [fibelatti/pinboard-kotlin#10]
This is pinkt 1.14.3 installed from Google Play on a Pixel 4a, Android 11.

My pinkt results were highly incomplete; comparing with pinboard on a web browser I saw my second link, and then maybe my 10th link, etc.  Pulling to refresh did not fix it.  I added a new link, and then did a PTR and then everything displayed correctly.

**Comment by fibelatti** [comment]
Hi @ahupp, thanks for reporting. I'll investigate to see if there are any issues with the caching strategy.

To give you some context, the Pinboard API enforces the usage of a timestamp check, which the app uses to see if it has the latest data. To avoid issues like this in the future I'll add an option to force the synchronization and that might help in these scenarios.

I'll let you know in this issue once I've issued an update.

**Comment by fibelatti** [comment]
Hi @ahupp, this issue was fixed in the version 1.15.0 released a few days ago.

Thanks for reporting, please don't hesitate to open another issue in case you find something else.

Many thanks.
