### ISSUE TITLE
Feature request: change date formats

### ISSUE THREAD

**Issue by josephrooks** [fibelatti/pinboard-kotlin#12]
Hi Filipe, thanks for this fantastic app. It's been the best Pinboard app I've tried on Android, as a brand new Android user.

I have one feature request if you find the time - could you add a toggle to flip the month and day in the date format?

**Comment by fibelatti** [comment]
Hey @josephrooks, thanks for the feedback! I'm glad you're satisfied with the app experience.

Thanks for the suggestion, I'll add this feature in an upcoming update, probably at the end of the month or early March.

**Comment by fibelatti** [comment]
Hi @josephrooks, thanks for your patience! I just submitted version 1.16.0 to the Play Store with a new preference to customise the date format. Enjoy!

**Comment by polm** [comment]
Thank you for adding this feature! I was very happy to see the option added recently but unfortunately I'm actually not very used to either of the current formats. Could you also add YY/MM/DD?

Thanks for the great app!
