### ISSUE TITLE
Toggle read later in quick actions

### ISSUE THREAD

**Issue by noamross** [fibelatti/pinboard-kotlin#129]
Setting a site as read or to read is probably my most common action. Could this be quick action or be done by swiping bookmarks? Thanks.

**Comment by fibelatti** [comment]
Hi @noamross, thanks for the suggestion! I'll update the quick actions menu to include a read later toggle, I'm already working on the next update and it should be available in the next few days.

**Comment by fibelatti** [comment]
Hi @noamross, this feature is now live on version 1.24.

Thanks for the suggestion!
