### ISSUE TITLE
Returning to app from browser reopens last bookmark

### ISSUE THREAD

**Issue by k-obrien** [fibelatti/pinboard-kotlin#176]
Opening bookmarks in the external browser then returning to the app causes the browser to reopen with the selected bookmark.

What I expect to happen: The app remains on the list of bookmarks

What actually happens: The last selected bookmark is reopened in the external browser

Steps to reproduce:
1. Set `Viewing bookmarks` to `Use external browser`
2. Select any bookmark
3. Return to Pinkt by using back button OR back gesture OR quitting browser

**Comment by fibelatti** [comment]
Hi @k-obrien, thanks for reportting this issue! I'll do some investigation and include the fix in the next release.

**Comment by fibelatti** [comment]
Hi @k-obrien, this issue has been fixed in version 1.24.1 which will begin rolling out today.

Thanks for reporting!

**Comment by k-obrien** [comment]
Fantastic! Thank you.
