### ISSUE TITLE
API error?

### ISSUE THREAD

**Issue by edsu** [fibelatti/pinboard-kotlin#177]
In the last day or so I've noticed errors when submitting new bookmarks. 

![Screenshot_20230603_151415_Pinkt.jpg](https://github.com/fibelatti/pinboard-kotlin/assets/33829/0b6b1594-225f-4f3e-9b6f-d6eae481452a)

When I update the token, it continues to behave the same way.

I don't know if recent changes at Pinboard might be related?

https://twitter.com/Pinboard/status/1665100099666550786

**Comment by fibelatti** [comment]
Hi @edsu, thanks for reportting and linking the thread! I'll investigate the issue and submit and update if needed!

**Comment by edsu** [comment]
Thanks @fibelatti! I'm seeing a 500 error when adding a bookmark with Pinboard-Firefox, so it doesn't appear to be a Pinkt specific problem?

**Comment by fibelatti** [comment]
@edsu that's correct, I was just inspecting the logs and Pinkt is also receiving 500 errors when trying to add. The operation goes through but clients have to rely on a response containing `result code="done"` to be certain. We'll have to wait until the API maintainer fixes the issue. I'll keep an eye on it in case it requires a client change but I don't expect it.

**Comment by edsu** [comment]
Seems resolved now!
