### ISSUE TITLE
Use selected text as description

### ISSUE THREAD

**Issue by ecogit** [fibelatti/pinboard-kotlin#194]
As known from the desktop browser add-ons [Pinboard Plus](https://github.com/clvrobj/Pinboard-Plus) (Chrome) and [Pinboard Pin](https://github.com/Cito/Pinboard-Pin) (Firefox).

Precisely, they automatically enclose the description in blockquote tags when it's populated from the window's current selection.

Example:

![image](https://github.com/fibelatti/pinboard-kotlin/assets/706228/7a741a9c-82bf-4c4f-9ff4-a2ff92893c6f)

![image](https://github.com/fibelatti/pinboard-kotlin/assets/706228/fac3bfa5-8e59-496c-9b4c-f26e701e730b)

Of course Pinkt is already great as it is and it's not super much extra work to manually blockquote, but it still would be a welcome addition. 

It seems that increasingly Pinboarders are making use of this functionality, which makes the resulting bookmark more reader-friendly and easier to distinct what the bookmarker wrote / summarised and what has been "quoted" directly from the website.

Not being a programmer myself, I'm afraid I can't prepare a Pull-request. Also I don't know whether Android's permissions even allow such a functionality.

**Comment by fibelatti** [comment]
@ecogit thanks for the suggestion! That's a simple addition so I'll be sure to include this feature in the next update

**Comment by ecogit** [comment]
@fibelatti    Fabulous, looking forward :)

**Comment by fibelatti** [comment]
@ecogit version 2.0 is being rolled out in the Play Store and it includes better support for blockquotes. I'm gonna close this issue for now but if you have any feedback or request for changes don't hesitate to reopen it or open another one!

**Comment by ecogit** [comment]
Thank you @fibelatti for this leapfrog development to version 2.0! First impression is very good and now with blockquotes the description part is even better readable :)

To make even better use of the description area, I'd allow the usage of the Enter-key / New Line-key, so it becomes possible to format / segment the text. Like this it becomes even more beneficial to manage/label blockquote sections.

Or shall I open a new issue for this optimisation request?

**Comment by fibelatti** [comment]
@ecogit I'm already working on the next patch so I'll be sure to include this change as well, thanks for the suggestion!

**Comment by fibelatti** [comment]
@ecogit this change is being release later today, thanks for the suggestion!

**Comment by ecogit** [comment]
Wonderful, it works as desired. Grazie mille @fibelatti

**Comment by fibelatti** [comment]
@ecogit may I ask which browser are you using? The app already offers the desired functionality but unfortunately afaik only Chrome is able to share the highlighted text plus the URL, in which case the highlighted text will always have precedence over any SEO descriptions.

Firefox shares either the highlighted text or the URL and I'm not sure about other browsers as I don't use them myself.
