### ISSUE TITLE
Add support for blocking screenshots from being taken

### ISSUE THREAD

**Issue by grrrrr** [fibelatti/pinboard-kotlin#201]
I am aware that this is not a perfect privacy solution and there are ways around it but it would be useful to have PinKT block the ability to take screenshots.

While the risks / concerns of someone remotely taking a screenshot of PinKT on most peoples devices phone are low there are still users who may be more high risk, it is a possibility that some malware is setup to take screenshots of the recorded data and could result in issues in restrictive countries

Additionally with screenshots blocked, switching apps would result in you seeing PinKT is your list of open apps but not seeing the contents.

My suggestion would be to add a toggle allowing users to opt-in to this feature in the preferences screen.

Some apps that do that have this option if examples/comparison is needed

  * KeepassDX (always blocked)
  * Signal (allows toggling screenshot capture on or off)
  * ProtonMail (allows toggling screenshot capture on or off)
  * Aegis (allows toggling screenshot capture on or off)
  * MediLog (allows toggling screenshot capture on or off)
  * RedReader (allows toggling screenshot capture on or off)
  * Quacker & Fritter (allows toggling screenshot capture on or off)

**Comment by fibelatti** [comment]
Thanks @grrrrr, that's a great suggestion! I'll work to add it to the next release and it will be exactly as you described it, optional with a new toggle added to the preferences screen.

**Comment by fibelatti** [comment]
@grrrrr this will be available in the next release which is likely to go out in the next couple weeks or so, there are a few other things that I want to include as well. Thanks for the suggestion!
