### ISSUE TITLE
Overlay prevents clicking menu

### ISSUE THREAD

**Issue by sheymans** [fibelatti/pinboard-kotlin#203]
hey,

android v10
Galaxy S9

the menu item is hidden behind some overlay. Seems to be a recently introduced issue.

![Screenshot_20230903-103249_Pinkt](https://github.com/fibelatti/pinboard-kotlin/assets/2865995/0b351f00-7f6a-44c0-9f7d-e223259b94d2)

**Comment by fibelatti** [comment]
Hi @sheymans, thanks for reporting and sharing the device model and OS version. I thought I had this scenario covered but it might be something specific to Android 10 or Samsung.

I'll take a look again and release a fix, apologies for the inconvenience in the meantime.

**Comment by sheymans** [comment]
thanks @fibelatti !!

**Comment by fibelatti** [comment]
@sheymans this issue is now fixed, I'm releasing an update later today. Thanks for reporting!

**Comment by sheymans** [comment]
that's awesome @fibelatti ; thanks for the quick fix!!
