### ISSUE TITLE
Dark theme contrast issues

### ISSUE THREAD

**Issue by grrrrr** [fibelatti/pinboard-kotlin#207]
When in the dark mode theme,  the bottom bar in the main screen is somewhat hard to see with a number of the options being black on dark blue,  compared to the add new bookmark button which is pale blue(?) on dark blue.

These black buttons seem to be carried over from the light theme.

light
![light](https://github.com/fibelatti/pinboard-kotlin/assets/1025506/88fa482b-a1f3-4093-bb3d-fb6591e106cc)

dark 
![dark](https://github.com/fibelatti/pinboard-kotlin/assets/1025506/d2bb0799-225e-4d45-8e19-8df9fefc7860)

**Comment by fibelatti** [comment]
Thanks @grrrrr! I have reviewed the colors and the bottom bar will be fixed in the next update

**Comment by fibelatti** [comment]
@grrrrr the fix is now available in version 2.2. Thanks for reporting it!
