### ISSUE TITLE
Quick share

### ISSUE THREAD

**Issue by grrrrr** [fibelatti/pinboard-kotlin#208]
Currently the share to pinboard will open a screen allowing you to add tags and update the information of the bookmark.

It would be useful to also have a "quick share" option,  that would allow you to add a bookmark skipping all manual input or extra steps

e.g. 

regular share

- share link select `share to pinboard`
- enter tags / other details
- save
- be brought back to the page you wanted to bookmark

quick share

- share a link and select `quick share to pinboard` 
- bookmark autosaves
- be brought back to the page you wanted to bookmark with no other interaction

-

**Comment by fibelatti** [comment]
Thanks @grrrrr! That's currently possible to configure via the user preferences, but it would be always one or the other. I can see how having the two share options at the same time could be beneficial. I'm gonna look into adding support for that, thanks for the suggestion.

**Comment by fibelatti** [comment]
Coming soon 👀 

<img width="300" alt="image" src="https://github.com/fibelatti/pinboard-kotlin/assets/3277516/83add745-ea15-437b-96cd-18bbd4bb05ec">

**Comment by grrrrr** [comment]
Looks great.

Maybe only small change suggestion  have it "Quick save to..."  to match "Save to..." wording

**Comment by fibelatti** [comment]
@grrrrr this feature is now available in version 2.2. Thanks for suggesting it!
