### ISSUE TITLE
When sharing via browser select either Create (if URL does not exist) or Edit (if URL exists)

### ISSUE THREAD

**Issue by tohagan** [fibelatti/pinboard-kotlin#23]
Thank you very much for Pinkt - I'm a big fan!

## Idea 1 

Currently when you Share a new site via your browser, it always Creates a new pinboard record.  This is contrary to the UX used by pinboard's desktop browser scripts and means you end up with duplicate sites. Much smarter would be to first check if the URL has already been saved to decide if you should Create a new bookmark or Edit the existing one. 

## Idea 2

When I first installed Pinkt I though that I had to add new bookmarks from the browser (via Share ...) and then go to the app to edit them.  So I thought the app UX was a bit weird and limited (I would have given it a low rating). It wasn't until **much** later that I discovered you can turn on an option to show the Pintk bookmark editor immediately when sharing.  IMHO, this should be the default when you install the app as that's by far the most convenient, efficient and "expected" way to work.  Fix the issue in **Idea 1** and it's now perfect and best UX for a first time user.

**Comment by fibelatti** [comment]
Hi @tohagan, thank you for getting in touch! I'm very happy to know that you enjoy the app. Here's my reply to your suggestions:

**Idea 1** — The app already differentiates between new and existing bookmarks but it relies entirely on Pinboard to know this. Unlike the desktop browser, the REST API which 3rd party clients have to use doesn't offer an "edit" option or even a way to submit the existing bookmark ID to ensure that the existing entry will be updated instead. All clients can do is use the same service endpoint to save a bookmark by passing its details and that endpoint uses the URL to either create or update an entry. What I saw happening in my own experience is that some sites (like Medium) or URLs shared from social (which will contains marketing params like `utm_source`) can change slightly and that would cause duplicate entries to be created. The Pinboard owner is working on a v2 of its REST API which will solve this issue but until then there's not a lot that I can do.

**Idea 2** — Thanks for the feedback on this and I'm sorry that the app let you down for a long while! When the app first came about these features didn't exist so as I added them (and their accompanying settings) I had them turned off by default to avoid disrupting the existing experience. I'll make them the default behavior as I totally agree with your points.

If you have any other feedback or feature suggestion please don't hesitate to reach out!

Many thanks and best regards.

**Comment by christianhans** [comment]
Would it be possible to fetch the existing bookmark details (title, description and tags) when editing an existing bookmark? I think there are a few Pinboard Apps on iOS that seem to do that.

**Comment by fibelatti** [comment]
@christianhans oh this is definitely a bug! When @tohagan first reported this issue I was under the impression that the app was working as it should based on my own usage of Pinboard, but after doing some more extensive testing I now realize it is not and it's actually embarrassing that it has been like this for so long now 😅

I'm already working on a fix and it should be available in the upcoming days. I apologize for any inconvenience this may have caused!

**Comment by fibelatti** [comment]
@tohagan @christianhans this issue has been fixed in version 1.20.3, rolling out today to the Play Store. Thanks for reporting and for your patience!

**Comment by tohagan** [comment]
Excellent news! Thanks very much 😀 👍

**Comment by christianhans** [comment]
Works great, thanks! 👍
