### ISSUE TITLE
Sorting appears broken

### ISSUE THREAD

**Issue by k-obrien** [fibelatti/pinboard-kotlin#232]
Lately I have noticed that sorting of bookmarks appears broken. Assuming that sorting is alphabetical, bookmarks don't appear in the expected order. I think this change has only been introduced recently.

<img src="https://github.com/fibelatti/pinboard-kotlin/assets/53217276/e7b1a887-f640-484e-8ba9-94baff2512ab" width="250px" />
<img src="https://github.com/fibelatti/pinboard-kotlin/assets/53217276/10ca0672-b12d-44a0-b25d-fbaa713c0568" width="250px" />

**Comment by fibelatti** [comment]
Hi @k-obrien, sorting is not alphabetical. At the moment you can only sort by save date, changing between newest first or oldest first. I'll look into support other sorting methods in the future.

I'll close this as not an issue, but feel free to re-open it if you have further questions.

Thanks for using the app!

**Comment by k-obrien** [comment]
Ah, that explains it. I'm happy to raise a PR if you'd take it. Obviously you'd need to let me know how you'd like to implement multiple sorting options. Off the top of my head, tapping the sort button would pop up a menu with four options; one each of ascending and descending for save date and alphabetical, but you might prefer something else.

**Comment by fibelatti** [comment]
@k-obrien thanks for volunteering and apologies for the delayed response, I had to take some time away. I'm happy to say that this feature is coming to the [next release](https://github.com/fibelatti/pinboard-kotlin/commit/8a120c46e23da0392ef14af54d50fafd6147fd53) (date TBD). It's gonna work exactly as you described, tapping the sorting icon will bring up a selection menu similar to how the preferences screen works and there are 2 new sorting options, hopefully this will address your needs.

**Comment by k-obrien** [comment]
> @k-obrien thanks for volunteering and apologies for the delayed response, I had to take some time away.

No problem.

> I'm happy to say that this feature is coming to the next release

Amazing, thank you!
