### ISSUE TITLE
trying to share from Firefox: "Oops! Something went wrong"

### ISSUE THREAD

**Issue by rubaboo** [fibelatti/pinboard-kotlin#3]
Installed the app today and cannot share from Firefox. Samsung Galaxy S9, Android 9 with current patch from Samsung, not rooted. Current Firefox from Play Store.
The app itself starts and works ok.

**Comment by fibelatti** [comment]
Hi @rubaboo, sorry it took a while to respond. Is this still an issue?

**Comment by rubaboo** [comment]
No, it started working. No problems now.

**Comment by fibelatti** [comment]
@rubaboo that's great, thanks for letting me know. If you find any other issues please don't hesitate to reach out.
