### ISSUE TITLE
linkding login failed on v3.0

### ISSUE THREAD

**Issue by OPerepadia** [fibelatti/pinboard-kotlin#306]
Hi,
I can't login to linkding instance using v3.0 release of the app (tried F-Droid version and version from GitHub releases). I tested the pre-release apk from this link: https://github.com/fibelatti/pinboard-kotlin/actions/runs/9538926223 and it didn't have this issue.
I've also submitted an email report from the app.
Thanks

**Comment by fibelatti** [comment]
Hi @OPerepadia, thanks for filing the issue and submitting the in-app report. The pre-release version had cleartext traffic enabled as it's a build meant for debugging. That type of communication is disabled by default on Android as it's not secure, but apparently I'll have to enable it for Linkding.

I'll do that later today and submit a patch version.

**Comment by fibelatti** [comment]
@OPerepadia this issue should be fixed in [v3.0.1](https://github.com/fibelatti/pinboard-kotlin/releases/tag/v3.0.1). Apologies for the inconvenience and thanks once again for reporting!

I'll close the issue as resolved, but feel free to reopen it if that isn't the case.
