### ISSUE TITLE
[Feature Request]: Sort by date_added

### ISSUE THREAD

**Issue by djl** [fibelatti/pinboard-kotlin#324]
### Describe your idea

Currently (at least with linkding) the sort-by-date option sorts by the `date_modified` field from the API. Could we add an option to sort by `date_added` instead?

### Describe how you think it could work

Another option is added to the list of sorting options that sorts only by `date_added`.

**Comment by fibelatti** [comment]
Hi @djl, thanks for submitting this request! I'm gonna make it available in the next update
