### ISSUE TITLE
[Feature Request]: Do not follow redirects when saving bookmarks

### ISSUE THREAD

**Issue by djl** [fibelatti/pinboard-kotlin#330]
### Describe your idea

Today I bookmarked a link that is behind a login. If that URL is accessed when not logged in you are redirected back to a login page. I just noticed that the bookmark's URL and title was updated to the login page, rather than the URL I had originally bookmarked.

Possibly related to https://github.com/fibelatti/pinboard-kotlin/issues/6

### Describe how you think it could work

Instead of following redirects allow the user to keep the original URL, title, etc.

This might break existing functionality so it might make sense to put it behind a user option.

**Comment by fibelatti** [comment]
Hi @djl, thanks for submitting this issue! Indeed, this will have to be a new user setting to avoid disrupting the existing behavior.

I'll work on it for the next update, coming in a couple weeks.

**Comment by fibelatti** [comment]
Hi @djl, a new setting was added to version 3.2.0 which was released to Google Play today. Thanks for your request!
