### ISSUE TITLE
[Bug]: "Mark as read on open" and "Edit bookmark" options on Linkding 1.36.0 are broken

### ISSUE THREAD

**Issue by TH0MVS** [fibelatti/pinboard-kotlin#335]
### Describe the problem

Mark as read on open option don't work anymore on latest version of Linkding (1.36.0). The Edit bookmark option seem to be broken too.

There is some changes on API, some maybe its the source of the problem :
> Do not clear fields in POST requests (API behavior change) by @sissbruecker in https://github.com/sissbruecker/linkding/pull/852

### Device model

Google Pixel 7

### Android version

Android 14 (GrapheneOS)

### App version

3.1.1

**Comment by fibelatti** [comment]
Hi @TH0MVS, thanks for reporting this issue. I'll investigate it in the next couple days and report back, fixing it in an upcoming update if needed.

@sissbruecker as soon as I have more details I'll share here, thanks for the additional context.

**Comment by TH0MVS** [comment]
Thanks a lot for your replies. Great softwares by the way, they really fit well in my reading workflow !

Well, I tried again and no, bugs are still here.  I'm using linkding:latest-plus image, which deploy 1.36.0 release. I tried linkding:1.35.0-plus, no problem with this release.

I was wrong about the Edit option. Its only the Read Later statut that dont work. 

So to make things clear:
- When "Mark as read" is enabled in the app option, expected behaviour is when you press on a link, it remove the read later statut. On 1.36.0, it move the bookmarks to the top of the list, open the link, but dont remove the read later statut
- When you long press a link and select "Remove from Read Later", expected behaviour is, well, remove the read later statut. On 1.36.0, it move the bookmarks to the top of the list, open the link, but dont remove the read later statut (yes, the same thing as previous)
-  When you long press a link and select "Edit bookmark", it open the Save bookmark page. You can disable Read later then press the save icon on bottom right. And again, you guessed it : it move the bookmarks to the top of the list, open the link, but dont remove the read later statut.

**Comment by fibelatti** [comment]
@TH0MVS thanks for sharing all of that, I updated my linkding instance to the latest and I'm able to reproduce the issue. From what I can tell, adding a bookmark to read later works as expected, but removing it doesn't work. After inspecting the network logs I can see that for some reason the `unread` field is not being sent, which is why the status is never removed.

I'll investigate it further to understand what happened since this hasn't changed and I expect to release a fix soon enough. Apologies for the inconvenience in the meantime.

**Comment by fibelatti** [comment]
@TH0MVS I have identified the issue and fixed it in version 3.2.0, which should be available on Google Play shortly. Thanks for reporting!

@sissbruecker the REST API is working as expected, the issue was within my serialization setup.
