### ISSUE TITLE
[Bug]: Bookmarks were wiped during prolonged Linkding server outage

### ISSUE THREAD

**Issue by caferen** [fibelatti/pinboard-kotlin#345]
### Describe the problem

My self hosted Linkding server was down for about 10 days recently and I noticed that the app purged all bookmarks after some days of not being able to reach the server, I don't know the exact duration that triggered the issue.

Sidenote: It is also not able to queue a bookmark for saving when the server is offline, it hangs indefinitely.

### Device model

Samsung Galaxy S24

### Android version

Android 14

### App version

 3.1.1

**Comment by fibelatti** [comment]
Hi @caferen, thanks for reporting this issue. That's a bit odd considering how the local cache is only cleared in 2 situations:

1. **After** successfully fetching bookmarks from the server; the old cache is purged, and a new one is saved
2. **After** successfully logging in; the old cache is purged, and a new one is started fresh for the new user. A successful login immediately triggers a request to fetch all bookmarks

So the app wouldn't have deleted local data on its own. Were you still logged in when that happened?

> It is also not able to queue a bookmark for saving when the server is offline, it hangs indefinitely.

I'll improve how this feature works. Currently bookmarks are only queued when the device is offline, but doing the same when the server is offline is a good idea! You can expect to see this improvement in the next release

**Comment by caferen** [comment]
Hi @fibelatti, I've set up the app again and realized there was a bug with the version I was on that caused the bookmarks to disappear. I cannot confirm this as I had to upgrade from the fdroid version to GitHub version so the app data was deleted but that was probably the cause.

Thanks for looking into the offline server handling. I've recently found out that most self-hosted server frontends don't handle that case at all.

Feel free to close the bug.

**Comment by fibelatti** [comment]
@caferen ah, that was definitely it! You won't face that again if you're using 3.2.2, regardless of how long the app is unable to reach the server. I'll leave the issue open until I ship the improvements to pending sync bookmarks, this way I can post updates here to let you know about its progress.

**Comment by fibelatti** [comment]
@caferen the changes to how pending sync works is now available in version 3.3.0, thanks for the suggestion!
