### ISSUE TITLE
[Bug]: Pinboard descriptions are wrapped in <blockquote>... </blockquote>

### ISSUE THREAD

**Issue by tohagan** [fibelatti/pinboard-kotlin#359]
### What happened?

I love Pinkt and use it constantly. Thank you!!

The only annoying bit is that it adds `<blockquote>`... `</blockquote>` to descriptions. 
Can we remove this or have an option to do disable?

### Service

Pinboard

### Device model

Samsung A13 and A70 

### Android version

Android 14

### App version

3.3.3

**Comment by fibelatti** [comment]
Hi @tohagan, thanks for using the app and contributing with this issue! 

> The only annoying bit is that it adds <blockquote>... </blockquote> to descriptions.

That's totally fair. I shamelessly copied the behavior from a browser extension without really considering that some people might not want that. I'll make this optional in the next release, with a new setting. I reckon the next version should become available in the next week or two, so just bear with me for a little while longer.

**Comment by fibelatti** [comment]
Hi @tohagan, version 3.4.0 will include a new setting to control this behavior. The update will begin rolling out soon. Thanks for your suggestion!

**Comment by ptc-tonyo** [comment]
Thank you!! Greatly appreciated.

**Comment by tohagan** [comment]
Thank you!! Greatly appreciated.
