### ISSUE TITLE
Saving Duplicate Link Destroys User Data

### ISSUE THREAD

**Issue by thedward** [fibelatti/pinboard-kotlin#5]
| |  |
|---:|---:|
|Android Version|10|
|App Version|1.70|

I would have expected saving a link to be a safe operation and that any existing metadata would be preserved.

However, my expectations have been thwarted, as when I save a duplicate link, any existing tags or description are _heartlessly deleted_.

**Comment by fibelatti** [comment]
Hi @thedward thanks for reporting it, I'm sorry that this is happening.

I'll look into it and publish a fix soon.

**Comment by fibelatti** [comment]
Hi @thedward, this issue is now fixed. It is included in release `1.8.2` which I published to the Play Store today.
