### ISSUE TITLE
Wayback Machine Links Transformed into Original URL

### ISSUE THREAD

**Issue by thedward** [fibelatti/pinboard-kotlin#6]
| |  |
|---:|---:|
|Android Version|10|
|App Version|1.8.2|

When I try and save a link (via the share menu) to an archived page at the [Internet Archive Wayback Machine](https://archive.org/web/), it gets transformed into a link to the original URL of the archived page.

For example: 
‘<https://web.archive.org/web/20111117040806/http://www.pauljoycegerman.co.uk/pronounce/index.html >’ 
gets turned into: 
‘<http://www.pauljoycegerman.co.uk/pronounce/index.html>’.

It works as expected if I add a new link in the app and paste in the URL.

**Comment by fibelatti** [comment]
Hi @thedward, thanks for reporting I'll look into it.  When sharing to the app, it will try to resolve the URL mainly to avoid redirections that things like social media and medium use, but I see that it can be an undesired behaviour on the use case you mentioned.

I'll look into adding an option in the settings menu to always keep the original URL.

**Comment by fibelatti** [comment]
Hi @thedward, thanks for your patience. The issue was something else actually, I fixed it in the version submitted to the Play Store today (1.9.1).
