### ISSUE TITLE
Mobile.twitter links fail to save from the share sheet

### ISSUE THREAD

**Issue by maxkrieger** [fibelatti/pinboard-kotlin#7]
Reproduce:
Navigate to a mobile.twitter link via chrome eg

https://mobile.twitter.com/varguyart/status/1246334627788345345

Open the share sheet from the chrome menu and share to pinkt

"Oops, something went wrong"

I'm guessing this has to do with the autopopulating fields feature? Maybe a unicode issue?

**Comment by fibelatti** [comment]
Hi @maxkrieger! Yes, that's most likely the case. The share menu will attempt to resolve the URL so that it can populate certain fields like the title and description. I'll look into it to fallback in case an error happens.

**Comment by fibelatti** [comment]
Hi @maxkrieger, thanks for your patience. I fixed this issue in the next version (1.9.1) release to the Play Store today.
