### ISSUE TITLE
Ability to sort pinboard notes by date or alpha

### ISSUE THREAD

**Issue by e441e** [fibelatti/pinboard-kotlin#8]
Hi, Thanks for this awesome pinboard app.

Currently, the notes are randomly sorted. Is there any way you can allow sorting by date or alphabetically?

**Comment by fibelatti** [comment]
Hi @e441e, thanks for the suggestion! I'll add this feature to next release.

**Comment by fibelatti** [comment]
Hi @e441e, I added this feature in the next version (1.9.1) release to the Play Store today.

**Comment by e441e** [comment]
hi there, thanks for the quick addition. I am unsure why but when I tried to sort by newest, it will not load from the top of my latest notes. It will start to load the notes that's created from last month and I have to manually scroll up to the latest notes. Is there any way for it to show the latest notes without having to scroll all the way up?

**Comment by fibelatti** [comment]
@e441e sure, I'll improve the behaviour in the next release.

**Comment by fibelatti** [comment]
@e441e thanks for your patience, this behaviour was fixed in the update released yesterday (v1.11.0).
